version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: test
      POSTGRES_DB: quest
    volumes:
        - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    command: "make runserver"
    working_dir: /usr/src/app
    environment:
      QUEST_DATABASE_HOST: db
    depends_on:
      - "db"
    volumes:
      - ".:/usr/src/app"

  static:
    image: node:latest
    command: "make watch_static"
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"

  test:
    build: .
    environment:
      QUEST_DATABASE_HOST: db
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
