# Generated by Django 2.1.4 on 2018-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='The title of the goal')),
                ('description', models.TextField(help_text='The description of the goal')),
                ('summary_image', models.ImageField(help_text='An image for the goal', upload_to='goals')),
                ('slug', models.SlugField(help_text='The text for this goal used in its URL', max_length=100)),
            ],
        ),
    ]
