# Generated by Django 2.1.4 on 2018-12-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='summary_image',
            new_name='image',
        ),
    ]
