# Generated by Django 2.1.4 on 2018-12-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20181226_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.TextField(default='Goal', help_text='The name of the goal'),
            preserve_default=False,
        ),
    ]
