# Generated by Django 2.1.4 on 2018-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20181228_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(help_text='The name of the goal', max_length=255),
        ),
    ]
