# Generated by Django 2.1.4 on 2019-01-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20181229_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='percentage_complete',
            field=models.PositiveIntegerField(default=0, help_text='The percentage of the goal complete'),
            preserve_default=False,
        ),
    ]
