# Generated by Django 2.1.4 on 2019-01-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goal_percentage_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='percentage_complete',
        ),
    ]
