# Generated by Django 2.1.4 on 2019-01-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20190104_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether or not this task is complete'),
            preserve_default=False,
        ),
    ]
