# Generated by Django 2.1.4 on 2019-01-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20190115_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether or not this goal is publicly accessible'),
        ),
    ]
