# Generated by Django 3.0 on 2020-08-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_auto_20200804_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_tasks', models.PositiveSmallIntegerField(default=0, help_text='Completed tasks for this goal')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Started'), (2, 'Done')], default=False, help_text='The status of this task'),
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW goals_goalsummary AS
            SELECT "goals_goal"."id" as goal_id, CURRENT_DATE as "date",
               COALESCE((SELECT COUNT(U0."id") AS "count" FROM "goals_taskstatus" U0 INNER JOIN "goals_task" U1 ON (U0."task_id" = U1."id") WHERE (U0."status" = 2 AND U1."goal_id" = "goals_goal"."id") GROUP BY U1."goal_id"), 0) AS "completed_tasks"
            FROM "goals_goal"
            ORDER BY "completed_tasks" DESC;
            CREATE UNIQUE INDEX goals_goalsummary_pk ON goals_goalsummary(goal_id);
            """,
            """
            DROP MATERIALIZED VIEW goals_goalsummary;
            """
        )
    ]
