# Generated by Django 3.0 on 2021-01-06 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_auto_20200805_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['uuid'], name='goals_task_uuid_9c6856_idx'),
        ),
    ]
