# Generated by Django 2.1.4 on 2019-02-26 14:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Disable transactions, which are not supported by concurrent indexing.

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX CONCURRENTLY analytics_name_idx ON analytics_event(name);")
    ]
