# Generated by Django 2.1.4 on 2019-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_name_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='analytics_e_name_522cb6_idx'),
        ),
    ]
