# Generated by Django 3.0 on 2020-08-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20200804_2346'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='analytics_e_name_522cb6_idx',
        ),
    ]
