# Generated by Django 3.0 on 2020-08-05 06:24
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('analytics', '0008_auto_20200805_0604'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='event',
            index=models.Index(fields=['name'], name='analytics_event_name_idx'))
    ]
