# Generated by Django 3.0 on 2020-08-05 06:32
from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('analytics', '0009_auto_20200805_0624'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='event', name='analytics_event_name_idx')
    ]

