# Generated by Django 3.0 on 2020-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20200805_0632'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(name='goal_viewed'), fields=['name'], name='analytics_event_name_idx'),
        ),
    ]
