# Generated by Django 3.0 on 2020-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20200809_1949'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='analytics_event_name_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(_negated=True, name='goal_viewed'), fields=['name'], name='analytics_event_name_idx'),
        ),
    ]
