# Generated by Django 3.0 on 2020-08-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200804_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.OneToOneField(blank=True, help_text='The account to which this user belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Account'),
        ),
    ]
